name: Draft Release

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Draft GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_notes: true
          draft: true
